# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 22:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('count300', models.IntegerField()),
                ('count100', models.IntegerField()),
                ('count50', models.IntegerField()),
                ('playcount', models.IntegerField()),
                ('ranked_score', models.BigIntegerField()),
                ('total_score', models.BigIntegerField()),
                ('pp_rank', models.IntegerField()),
                ('level', models.FloatField()),
                ('pp_raw', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('count_rank_ss', models.IntegerField()),
                ('count_rank_s', models.IntegerField()),
                ('count_rank_a', models.IntegerField()),
                ('pp_country_rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MapInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.IntegerField()),
                ('approved_date', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('artist', models.CharField(max_length=255)),
                ('beatmap_id', models.IntegerField()),
                ('beatmapset_id', models.IntegerField()),
                ('bpm', models.FloatField()),
                ('creator', models.CharField(max_length=255)),
                ('difficultyrating', models.FloatField()),
                ('diff_size', models.FloatField()),
                ('diff_overall', models.FloatField()),
                ('diff_approach', models.FloatField()),
                ('diff_drain', models.FloatField()),
                ('hit_length', models.FloatField()),
                ('source', models.CharField(max_length=255)),
                ('genre_id', models.IntegerField()),
                ('language_id', models.IntegerField()),
                ('favourite_count', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('total_length', models.IntegerField()),
                ('version', models.CharField(max_length=255)),
                ('file_md5', models.CharField(max_length=255)),
                ('mode', models.IntegerField()),
                ('tags', models.TextField()),
                ('playcount', models.IntegerField()),
                ('passcount', models.IntegerField()),
                ('max_combo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('maxcombo', models.IntegerField()),
                ('count300', models.IntegerField()),
                ('count100', models.IntegerField()),
                ('count50', models.IntegerField()),
                ('countmiss', models.IntegerField()),
                ('countkatu', models.IntegerField()),
                ('countgeki', models.IntegerField()),
                ('perfect', models.BooleanField()),
                ('enabled_mods', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('rank', models.CharField(max_length=5)),
                ('pp', models.FloatField()),
                ('map_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_set', to='osugraphs.MapInfo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_set', to='osugraphs.User'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_point_set', to='osugraphs.User'),
        ),
    ]